filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml

#-------------------------- Elasticsearch output -------------------------------
output.elasticsearch:
  hosts: ["10.27.0.4:9200"]
  username: "elastic"
  password: "changeme"

#============================== Kibana =====================================

setup.kibana:
  host: "10.27.0.4:5601" # TODO: Change this to the IP address of your ELK server

  
#================================ Logging ======================================
logging.to_files: true
logging.files:
