---
- name: Configure Elk VM with Docker
  hosts: elasticsearch
  remote_user: azureuser
  become: true
  tasks:
    # install cron to update 
    - name: install upgrade cron
      cron:
          hour: "12"
          minute: "0"
          job: "/usr/bin/apt update && /usr/bin/apt -y upgrade && [[ -f /var/run/reboot-required ]] && reboot"

    # Use apt module
    - name: Install docker.io
      apt:
        update_cache: yes
        force_apt_get: yes
        name: docker.io
        state: present

      # Use apt module
    - name: Install python3-pip
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

      # Use pip module (It will default to pip3)
    - name: Install Docker module
      pip:
        name: docker
        state: present

      # Use command module
    - name: Increase virtual memory
      command: sysctl -w vm.max_map_count=24576

      # Use sysctl module
    - name: Use more memory
      sysctl:
        name: vm.max_map_count
        value: "24576"
        state: present
        reload: yes

    # Use docker_container module
    - name: download and launch a docker elk container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        # Please list the ports that ELK runs on
        published_ports:
            -  5601:5601  # kibana
            -  9200:9200  # elasticsearch
            -  5044:5044  # logstash

      # Use systemd module
    - name: Enable service docker on boot
      systemd:
        name: docker
        enabled: yes

